services:
  secop_contratos:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: sql-bdm-pssw
      MYSQL_DATABASE: secop_contratos
      MYSQL_USER: admin
      MYSQL_PASSWORD: sql-bdm-pssw
    volumes:
      - ./contratos:/var/lib/mysql
volumes:
  secop_contratos: